version: "3"
services:
    nodeapp:
        build: .
        volumes:
            - .:/usr/src/nodeapp
            - ../:/usr/src/firebasekey
            - /usr/src/nodeapp/node_modules
        command: npm run dev
